main: "io.github.mrsperry.artifacts.Artifacts"
name: ${project.name}
version: ${project.version}
api-version: "1.15"
description: "Independent world modifiers of various effects"
commands:
  artifacts:
    description: "Used to enable and disable artifacts"
    usage: "/artifacts <list | enable | disable | randomize>"